### ISSUE TITLE
MC-64836

### ISSUE THREAD

**Issue by WarlordWossman** [mrgrim/MUP#10]
Mobs "control" the minecart they are riding:
https://bugs.mojang.com/browse/MC-64836

Annoying bug when dealing with any mobs in minecarts, 99,9% sure it's around in 1.12.2 even if that version is not confirmed on the bugtracker.
I think carpet mod has a fix for this? Might be something fitting the theme for mup.

**Comment by mrgrim** [comment]
Will be in the next release. :)

https://github.com/mrgrim/MUP/commit/e610380521995c78282e062062462ae9f72b26ba
