### ISSUE TITLE
moving observers don't trigger with MC-109832

### ISSUE THREAD

**Issue by WarlordWossman** [mrgrim/MUP#11]
Seems like observers moved by pistons and slime don't update, afaik this bugfix should only prevent placed observers from updating. Toggeling off the patch restored normal behavior.
Testing this with other mods installed, if you cannot reproduce it let me know and I will check if it's some sort of interaction with another mod.

**Comment by mrgrim** [comment]
Funny, I actually thought of this while going to sleep last night. :) I'm going to try to get a release out today fixing it.

**Comment by mrgrim** [comment]
Fixed in https://github.com/mrgrim/MUP/commit/15abfacc3bc428ffe184301a2bd380de50d4ddbe available now in 1.3.3. Thanks for reporting!

**Comment by WarlordWossman** [comment]
Did you test this? For me they still don't trigger in 1.3.3 when moved, might check in an instance with just forge and mup if you say it works on your end.

**Comment by mrgrim** [comment]
I did another sets of tests with the 1.3.3 jar downloaded from the release page on a fresh world with forge 14.23.5.2847, and everything seems to be working fine. It's possible the prior release could have left observers in a weird state. :( Considering Forge hasn't lived a similar bug down in 2 years I hope I didn't end up breaking one of your worlds!

I tested the following:

* An observer pushed and pulled while attached to a slime block
* An observer pushed and pulled directly by a sticky piston
* An observer dropped by a sticky piston with a 1 gt pulse
* An observer pulled by a sticky piston with a 1gt pulse
* An observer pushed by a regular piston

If it's still not working for you, could you attach the output of the debug log?

**Comment by WarlordWossman** [comment]
Thanks for the detailed list, I hope I can get some testing done over the next few days. Still thinking it could be an interaction with quarks piston features causing this in my current saves so I will report back if I can rule that out and if so test further!

**Comment by mrgrim** [comment]
What version of quark? I can do some testing there as well.

**Comment by WarlordWossman** [comment]
Quark-r1.6-177 (with piston features on in the config, should be default tho):
https://www.curseforge.com/minecraft/mc-mods/quark/files/2759240

**Comment by mrgrim** [comment]
I actually get a crash with the 1gt tests with Quark. It seems it mucks about in the TE preventing one of the mixins from applying. Oh quark.. what have you done? :O

**Comment by mrgrim** [comment]
OK, give the 1.3.4 release a try and see if that resolves your issue.

**Comment by WarlordWossman** [comment]
Seems to work fine now, checked all the points on your list and not getting any issues with those.
