### ISSUE TITLE
MC-134989 patch conflicts with FoamFix "fasterPropertyComparisons"

### ISSUE THREAD

**Issue by zomabies** [mrgrim/MUP#2]
When MC-134989 patch and FoamFix `fasterPropertyComparisons` are both enabled, the game crashes before it reaches the main menu.

Tested on: 
[foamfix-0.10.1-1.12.2.jar](https://minecraft.curseforge.com/projects/foamfix-for-minecraft)
mup-1.2.0.jar
forge 14.23.4.2759

Crash log: https://paste.dimdev.org/ujakicuruq.mccrash

Relevant FoamFix config
```
# Optimizes blockstate property equals and hashCode methods. [default: true]
B:fasterPropertyComparisons=true
```

Workaround: Setting one of the mod configuration to false prevents the crash.

**Comment by mrgrim** [comment]
Thank you for the report! I've had very little time to perform compatibility testing, so these are very helpful. For now I would recommend using FoamFix's version and unticking the "Load Patch" configuration in EUP. 

I'll hold this open until I've had time to implement a general purpose conflict detection and resolution system that can auto-disable patches, disable the ability to configure them, and provide a useful notification to the user as to why.

**Comment by mrgrim** [comment]
Conflict management will be in the next release.

https://github.com/mrgrim/MUP/commit/8adf06077dac8fb9ed4a233f219496a54df0ab82

Closing.

**Comment by zomabies** [comment]
Thank you for fixing this!
