### ISSUE TITLE
Player Chunk Loaders

### ISSUE THREAD

**Issue by DeadlyMC** [mrgrim/MUP#4]
**This would allow to load areas in your world which will allow mob spawning in the area too.**
Similar to a feature from carpet mod 
**Link to the video showing the same feature:(Includes timestamp)**
https://www.youtube.com/watch?v=ehVi5vhq1Aw&t=299s

Its basically like a chunk loader but in a more vanilla format

This would make a lot of things possible in technical minecraft.....
You can load mob farms while doing something else or even load quarries

Would be great if you could add this feature :)

Thanks and Regards
-DeadlyMC

**Comment by Cyprex** [comment]
There are plenty of mods around with chunkloaders, can you justify this addition?

**Comment by DeadlyMC** [comment]
Have you watched the video?And the the mods you are talking about just don't keep the vanilla feel in the game...I am pretty sure this mod does aim to keep the vanilla feel

**Comment by mrgrim** [comment]
A "fake player" is a feature addition out of scope for this mod. I do have ideas for an optimization/tweak that will eliminate the player presence requirement for things like crop growth by eliminating the random tick requirement, but that won't produce all the behaviors of a fake player.

I'm not aware of any single purpose chunk loader mods that also enable random ticks and mob spawning. The Forge chunk loading API doesn't provide these features on its own, and it would require a core mod to accomplish I believe. I would like to see such a thing, just not here, I'm afraid.
