### ISSUE TITLE
TNT Duping for 1.13.X

### ISSUE THREAD

**Issue by DeadlyMC** [mrgrim/MUP#5]
TNT Duping is a really **important** **feature** for Tech MC.....But unfortunately was removed in 1.13
Would be great if it would be the same as 1.12 and all the TNT duping using contraptions like world eaters work the same and don't require any tweaking

**NOTE:Only Possible when 1.13 Forge comes out**

Thanks and Regards
-Deadly MC

**Comment by mrgrim** [comment]
I'll revisit this if and when a 1.13 port is made. I'm open to mechanics tweaks that re-introduce behaviors from other versions of the game, but previous bugs I want to handle carefully. It's not clear how difficult it would be to reproduce this behavior legitimately.
