### ISSUE TITLE
Observer Tweaks 

### ISSUE THREAD

**Issue by DeadlyMC** [mrgrim/MUP#6]
Observers are a really important redstone component in Minecraft.....
But there are some small things that make it annoying some times:

1)Transparent Observers:
If observers become transparent blocks this would help reduce lag significantly in flying machines

2)Observer Shouldn't Power when placed(1.12.x)
If observers won't give out a redstone signal when placed it would be great as it would make building flying machines much easier

3)Observer Non Update:
This can be in the form of a gamerule in which whenever you turn it on the obersvers just won't give out any signals.....This will be useful when building flying machines and other observer related contraptions.....they even wont power when a block is placed in front....Basically they will never give a signal until the gamerule is turned off again

Feel free to comment more tweaks :)

**Comment by Cyprex** [comment]
Transparent Observers would break redstone that relies on them being a solid block, like having a repeater going into an observer to power the block, wouldn't it?

**Comment by DeadlyMC** [comment]
I dont think changing lightOpacity will do that but i'm not sure about it though..............I can check that and comment back after i am back home

**Comment by DeadlyMC** [comment]
Actually even if observers aren't transparent ....you can't use them to power a block....I have tested it:
https://imgur.com/a/E2zzEsp

**Comment by mrgrim** [comment]
I'll address each independently:

1) The newlight optimization should significantly reduce server side lag of flying machines on its own without altering the properties of the observer block itself. Sadly, newlight does not solve client rendering performance for light updates. I'd rather figure out a way to optimize that.

2) This has a proper Mojira entry at MC-109832. Even though it is marked WAI, this was contradicted in MC-132521. I'm happy to implement this.

3) I'm still undecided on if this mod should include creative/technical tools. I want to be very careful about controlling scope here.

**Comment by DeadlyMC** [comment]
Thanks!

**Comment by mrgrim** [comment]
MC-109832 patch added, will be in next release.
