### ISSUE TITLE
Curseforge support for brainlets

### ISSUE THREAD

**Issue by HiggsBonbon** [mrgrim/MUP#7]
I'm less than educated on the intricacies of building from source, so could we get the compiled version on Curseforge? Or at the very least, a link to the built patch.

![image](https://user-images.githubusercontent.com/8272619/49841443-aecdca00-fd85-11e8-9e7c-ec8a70af13dd.png)

**Comment by DeadlyMC** [comment]
You can get releases here:
https://github.com/mrgrim/MUP/releases

**Comment by mrgrim** [comment]
Thanks @DeadlyMC! Closing.
